
name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.7", "3.10"]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python_version }}
      - name: Setup project with pip
        run: "pip install -e .[dev]"
      - name: Check formatting
        run: black --check sentry2csv
      - name: Lint code
        run: pylint sentry2csv
      - name: Check typings
        run: mypy sentry2csv
      - name: Run tests
        run: pytest --cov sentry2csv --cov-report=term-missing tests/
